{exec} = require "child_process"

option "", "--reporter [NAME]", "mocha test reporter"
 
task "test", "run tests", (options) ->
    exec "NODE_ENV=test
    ./node_modules/.bin/mocha
    --compilers coffee:coffee-script
    --reporter #{options.reporter or 'spec'}
    --require coffee-script
    --require test/test-helper.coffee
    --colors
    ", (err, output) ->
        throw err if err
        console.log output
